
name: 清除日志(ClearAction)
on:
  workflow_dispatch:
  schedule:
    - cron: '20 18 * * *'


jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete_workflow_runs
        uses: smallprogram/delete-workflow-runs@main
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 6
